import "/styles/index.scss";
import MainNav from "@/components/ui/navbars/MainNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#282828",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body style={{ display: "flex", flexDirection: "column" }}>
        <MainNav />
        {children}
      </body>
    </html>
  );
}
