import "/styles/index.scss";
import MainNav from "@/components/navbars/MainNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <MainNav />
        {children}
      </body>
    </html>
  );
}
